package filehandling;

public class RhymeString {
	private static final String REMEMBER = "Remember, remember the Fifth of November,\r\n"
			+ "The Gunpowder Treason and Plot,\r\n"
			+ "I know of no reason\r\n"
			+ "Why the Gunpowder Treason\r\n"
			+ "Should ever be forgot.\r\n"
			+ "Guy Fawkes, Guy Fawkes, t’was his intent\r\n"
			+ "To blow up the King and Parli’ment.\r\n"
			+ "Three-score barrels of powder below\r\n"
			+ "To prove old England’s overthrow;\r\n"
			+ "By God’s providence he was catch’d\r\n"
			+ "With a dark lantern and burning match.\r\n"
			+ "Holla boys, Holla boys, let the bells ring.\r\n"
			+ "Holloa boys, holloa boys, God save the King!\r\n"
			+ "And what should we do with him? Burn him!";
	
	private static final String LONDON_BRIDGE = "London Bridge is falling down,\r\n"
			+ "Falling down, falling down,\r\n"
			+ "London Bridge is falling down,\r\n"
			+ "My fair Lady.\r\n"
			+ "\r\n"
			+ "Build it up with wood and clay,\r\n"
			+ "Wood and clay, wood and clay,\r\n"
			+ "Build it up with wood and clay,\r\n"
			+ "My fair Lady.\r\n"
			+ "\r\n"
			+ "Wood and clay will wash away,\r\n"
			+ "Wash away, wash away,\r\n"
			+ "Wood and clay will wash away,\r\n"
			+ "My fair Lady.\r\n"
			+ "\r\n"
			+ "Build it up with bricks and mortar,\r\n"
			+ "Bricks and mortar, bricks and mortar,\r\n"
			+ "Build it up with bricks and mortar,\r\n"
			+ "My fair Lady.\r\n"
			+ "\r\n"
			+ "Bricks and mortar will not stay,\r\n"
			+ "Will not stay, will not stay,\r\n"
			+ "Bricks and mortar will not stay,\r\n"
			+ "My fair Lady.\r\n"
			+ "\r\n"
			+ "Build it up with iron and steel,\r\n"
			+ "Iron and steel, iron and steel,\r\n"
			+ "Build it up with iron and steel,\r\n"
			+ "My fair Lady.\r\n"
			+ "\r\n"
			+ "Iron and steel will bend and bow,\r\n"
			+ "Bend and bow, bend and bow,\r\n"
			+ "Iron and steel will bend and bow,\r\n"
			+ "My fair Lady.\r\n"
			+ "\r\n"
			+ "Build it up with silver and gold,\r\n"
			+ "Silver and gold, silver and gold,\r\n"
			+ "Build it up with silver and gold,\r\n"
			+ "My fair Lady.\r\n"
			+ "\r\n"
			+ "Silver and gold will be stolen away,\r\n"
			+ "Stolen away, stolen away,\r\n"
			+ "Silver and gold will be stolen away,\r\n"
			+ "My fair Lady.\r\n"
			+ "\r\n"
			+ "Set a man to watch all nigh,\r\n"
			+ "Watch all night, watch all night,\r\n"
			+ "Set a man to watch all night,\r\n"
			+ "My fair Lady.\r\n"
			+ "\r\n"
			+ "Suppose the man should fall asleep,\r\n"
			+ "Fall asleep, fall asleep,\r\n"
			+ "Suppose the man should fall asleep?\r\n"
			+ "My fair Lady.\r\n"
			+ "\r\n"
			+ "Give him a pipe to smoke all night,\r\n"
			+ "Smoke all night, smoke all night,\r\n"
			+ "Give him a pipe to smoke all night,\r\n"
			+ "My fair Lady.";
	
	private static final String MARY_LAMB = "Mary had a little lamb,\r\n"
			+ "whose fleece was white as snow.\r\n"
			+ "\r\n"
			+ "And everywhere that Mary went,\r\n"
			+ "the lamb was sure to go.\r\n"
			+ "\r\n"
			+ "It followed her to school one day\r\n"
			+ "which was against the rules.\r\n"
			+ "\r\n"
			+ "It made the children laugh and play,\r\n"
			+ "to see a lamb at school.\r\n"
			+ "\r\n"
			+ "And so the teacher turned it out,\r\n"
			+ "but still it lingered near,\r\n"
			+ "\r\n"
			+ "And waited patiently about,\r\n"
			+ "till Mary did appear.\r\n"
			+ "\r\n"
			+ "“Why does the lamb love Mary so?”\r\n"
			+ "the eager children cry.\r\n"
			+ "\r\n"
			+ "“Why, Mary loves the lamb, you know.”\r\n"
			+ "the teacher did reply";
	
	public static String getMary() {
		return MARY_LAMB;
	}
	public static String getLondon() {
		return LONDON_BRIDGE;
	}
	public static String getRemember() {
		return REMEMBER;
	}
}
